name: Argon.js Tutorials
markdown: redcarpet
highlighter: pygments
destination: _site/
permalink: tutorials/:title.html
description: Argon.js tutorial site.
baseurl: /pages/ael/argon-tutorials
paginate: 5